name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  design_x:
    path: ../
    version: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/sample.json
    - assets/images/orange.jpg
    - assets/svgs/fire.svg
    
  fonts:
    - family: Astronaut_PersonalUse
      fonts:
        - asset: assets/fonts/Astronaut_PersonalUse.otf
   