name: design_x
description: A toolkit for building custom design systems on top of any Flutter app, offering enhanced flexibility and scalability for your app's visual identity.
version: 0.0.1
# author: Kevin Kobori <kevinyujikobori@gmail.com>
homepage: https://www.linkedin.com/in/kevin-kobori/
repository: https://github.com/Fluttely/desing_x

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  mix: ^1.0.0
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0